console.log("This is an awesome feature!");
console.log("Testing husky commitlint");
console.log("New feature!");
console.log("New feature!");
console.log("New feature!");
console.log("New feature!");
console.log("New feature! - issue 68");
console.log("New feature!");
console.log("New feature!2");
console.info("This is a fix!2");
console.info("This is a fix!");
console.info("This is a fix!");
console.info("This is a fix! - issue-68");
